# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('task', models.CharField(max_length=1000, verbose_name='Условие')),
                ('answer', models.CharField(max_length=200, verbose_name='Ответ')),
                ('direction', models.CharField(max_length=200, verbose_name='Указание')),
                ('solution', models.CharField(max_length=200, verbose_name='Решение')),
                ('ts', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
