# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_remove_problem_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='solution',
            field=models.TextField(max_length=2000, verbose_name='Решение'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='task',
            field=models.TextField(max_length=2000, verbose_name='Условие'),
        ),
    ]
