# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20160124_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='grade_down',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, verbose_name='От класса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='grade_up',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, verbose_name='До класса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='more_info',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='direction',
            field=models.CharField(blank=True, max_length=200, verbose_name='Указание'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solution',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Решение'),
        ),
    ]
