# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20160206_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='_Tagulous_Problem_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='_Tagulous_Problem_theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(help_text='The name of the tag, without ancestors', max_length=255)),
                ('level', models.IntegerField(default=1, help_text='The level of the tag in the tree')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='problems._Tagulous_Problem_theme')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagTreeModel, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='_tagulous_problem_category',
            unique_together=set([('slug',)]),
        ),
        migrations.AddField(
            model_name='problem',
            name='category',
            field=tagulous.models.fields.SingleTagField(_set_tag_meta=True, blank=True, initial='school, olymp,science', null=True, on_delete=django.db.models.deletion.CASCADE, to='problems._Tagulous_Problem_category'),
        ),
        migrations.AddField(
            model_name='problem',
            name='theme',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', to='problems._Tagulous_Problem_theme', tree=True),
        ),
        migrations.AlterUniqueTogether(
            name='_tagulous_problem_theme',
            unique_together=set([('slug', 'parent')]),
        ),
    ]
