# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 19:32
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20160223_1848'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='_tagulous_problem_theme',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='_tagulous_problem_theme',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='theme',
        ),
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=tagulous.models.fields.SingleTagField(_set_tag_meta=True, blank=True, help_text='Категория', initial='school, olymp, science', null=True, on_delete=django.db.models.deletion.CASCADE, to='problems._Tagulous_Problem_category'),
        ),
        migrations.DeleteModel(
            name='_Tagulous_Problem_theme',
        ),
    ]
